apiVersion: steward.deis.com/v1
kind: "ServicePlanClaim"
metadata:
  name: test-service-plan-claim
  namespace: steward
service_provider: testProvider
service_plan: testPlan
claim_id: 452ca412-b55d-4601-8d17-eb2172499596
action: create
status: ignoredBySteward
status_description: ignoredBySteward
