apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #cf_broker_name#-steward
  namespace: steward
  labels:
    app: #cf_broker_name#-steward
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: #cf_broker_name#-steward
    spec:
      containers:
      - name: #cf_broker_name#-steward
        image: #steward_image#
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: trace
        - name: STEWARD_MODE
          value: cf
        - name: CF_BROKER_SCHEME
          value: "#cf_broker_scheme#"
        - name: CF_BROKER_HOSTNAME
          value: "#cf_broker_hostname#"
        - name: CF_BROKER_PORT
          value: "#cf_broker_port#"
        - name: CF_BROKER_USERNAME
          value: "#cf_broker_username#"
        - name: CF_BROKER_PASSWORD
          value: "#cf_broker_password#"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: #cf_broker_name#-steward
  namespace: steward
  labels:
    app: #cf_broker_name#-steward
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: #cf_broker_name#-steward
